name: Build documentation and pack

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  pack:
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: ${{ github.event_name == 'release' }}
        run: |
          git fetch --tags --force
          
      - name: Make gen_pack.sh executable
        run: chmod +x ./gen_pack.sh

      - name: Generate Pack
        uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2
          packchk-version: 1.3.96
          gen-pack-script: ./gen_pack.sh
          gen-pack-output: ./output

      - name: Copy .pack file
        run: cp ./output/kk.byte_queue.1.0.0.pack ./release/kk.byte_queue.1.0.0.pack

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          files: ./release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
